#!/bin/bash

export LC_ALL="id_ID.UTF-8"

STYLE_BOLD="\e[1;m"
STYLE_RESET="\e[0;m"

FORMAT_BOLD="${FORMAT_BOLD:-*}"

LAST_PATH="$HOME/Documents/School/Stuff/agenda/last"

setdate=${DATE_OVERRIDE:-tomorrow}
tanggal="`date -d "$setdate" '+%d %B %Y'`"
hari="`date -d "$setdate" '+%A'`"

j_pulang_tmp="14:35"

notion_secret="secret_g4o4Mj2hARo8vMSy4VLExEDE3agSqS5urMb7iFR2xLz"
notion_db_id="9ee5dd92b3a34f1082f9bd0a424e5e8c"

notion_integration_retrive_tasks(){
	set -e
	json_tasks=$(curl -X POST "https://api.notion.com/v1/databases/$notion_db_id/query" \
		-H 'Authorization: Bearer '"$notion_secret"'' \
		-H 'Notion-Version: 2022-06-28' \
		-H "Content-Type: application/json" \
		--data '{
			"filter": {
			"property": "Status",
			"status": {
			"equals": "Dalam pengerjaan"
		}
	} ,

	"sorts": [
	{
		"property": "Status",
		"direction": "ascending"
	},
	{
		"property": "Tenggat",
		"direction": "ascending"
	}
	]
}')

	tasks_count="$(jq '.results | length' <<< "$json_tasks" )"

	for ((j = 0; j < $tasks_count; j++))
	do
		eval pr+=("$(jq ".results[$j].properties.Tugas.title[0].plain_text" <<< "$json_tasks")")
		eval pr_mapel+=("$(jq ".results[$j].properties.Mapel.select.name" <<< "$json_tasks")")

		eval notion_tenggat_tmp=$(jq ".results[$j].properties.Tenggat.date.start" <<< "$json_tasks")

		if [[ $notion_tenggat_tmp == "null" ]]
		then
			pr_tenggat+=("null")
			continue
		else

			tenggat_tmp_month=$(date -d $notion_tenggat_tmp +%-m)
			tenggat_tmp_day=$(date -d $notion_tenggat_tmp +%-d)
			tenggat_tmp_year=$(date -d $notion_tenggat_tmp +%Y)

			# kalo minggu ini atau minggu depan, make the due human-readable...
			if [[ $((tenggat_tmp_year - $(date +%Y))) -eq 0 ]] && [[ $((tenggat_tmp_month - $(date +%m))) -eq 0 ]] && [[ $((tenggat_tmp_day - $(date +%d))) -lt 8 ]] 
			then
				rel_day="$(determine_rel_date $((tenggat_tmp_day - $(date +%d))))"
				case "$rel_day" in
					tomorrow)
						tmp_tenggat="besok"
						;;
					this_week)
						tmp_tenggat="$(date -d "$notion_tenggat_tmp" +%A)"
						;;
					next_week)
						tmp_tenggat="$(date -d "$notion_tenggat_tmp" +%A) depan"
						;;
				esac
			else
				tmp_tenggat="$(date -d "$notion_tenggat_tmp" '+%d %B' )"

			fi


			pr_tenggat+=("$tmp_tenggat")
		fi
	done

	set +e
	

}
mapels() {
	echo "📚 ${FORMAT_BOLD}Mapel${FORMAT_BOLD}"

	if [[ -n "$mapels_custom" ]]
	then
		for (( i = 0; i < ${#mapels_custom[@]}; i++ ))
		do
			echo "$(($i+1))) ${kode[${mapels_custom[$i]}]}"
		done

	else
		eval mapels="${mapel[$hari]}"

		for (( i = 0; i < ${#mapels[@]}; i++ ))
		do
			echo "$(($i+1))) ${kode[${mapels[$i]}]}"
		done

	fi

}

sep(){
	echo
	case "$(date +%b -d 'tomorrow')" in
		Jan)
			echo "🪅🎉🪅"
			;;
		Feb)
			echo "💐💌💗"
			;;
		Apr)
			echo "🐰🐰🐰"
			;;
		Agu)
			echo "🇮🇩🇮🇩🇮🇩"
			;;
		Des)
			echo "❄️☃️❄️"
			;;
		${FORMAT_BOLD})
			echo "---"
			;;
	esac
	echo
}

reverse_lookup_kode(){
	for i in "${!kode[@]}"
	do
		if [[ "${1@L}" == "${kode[$i]@L}" ]]
		then
			echo -en "$i:"
		fi
	done


}

determine_rel_date(){

	day_rel_no="$1"
	if [[ "$day_rel_no" -eq 1 ]]
	then
		echo "tomorrow"
	else
		if [[ "$(date -d "$day_rel_no days" +%u)" -le "$(($(date +%u)))" ]]
		then
			echo "next_week"
		else
			echo "this_week"
		fi
	fi
}

hint_next_mapel(){
	[[ -n "$DATE_OVERRIDE" ]] && return #current limitation

	IFS=":"
	read -a codes <<< "$(reverse_lookup_kode "$1")"
	IFS="
"
	for day_rel_no in {1..7}
	do
		day_rel="$(date -d "$day_rel_no days" +%A)"
		eval "mapel_codes=${mapel[$day_rel]}"
		for code_day in "${mapel_codes[@]}"
		do
			for code in "${codes[@]}"
			do
				if [[ "$code" == "$code_day" ]]
				then
					case "$(determine_rel_date "$day_rel_no")" in
						tomorrow)
							echo -e "\e[1;32mHint: mapel $1 yang berikutnya ada besok${STYLE_RESET}"
							;;
						next_week)
							echo -e "\e[1;32mHint: mapel $1 yang berikutnya ada pada hari $day_rel depan${STYLE_RESET}"
							;;
						this_week)
							echo -e "\e[1;32mHint: mapel $1 yang berikutnya ada pada hari $day_rel${STYLE_RESET}"
							;;
					esac
					return
				fi
			done
		done
	done

}

save_data(){
	# Save data
	mv "$LAST_PATH" "${LAST_PATH%/${FORMAT_BOLD}}/last.bak"
	cat > "$LAST_PATH"<< EOF
timestamp="$(date '+%-m%d%Y')"
last_renungan_1=${siswa_renungan_1:-$last_renungan_1}
last_renungan_2=${siswa_renungan_2:-$last_renungan_2}
last_doa_pulang=${siswa_doa_pulang:-$last_doa_pulang}
senin_last_piket=(${senin_last_piket[@]})
selasa_last_piket=(${selasa_last_piket[@]})
rabu_last_piket=(${rabu_last_piket[@]})
kamis_last_piket=(${kamis_last_piket[@]})
jumat_last_piket=(${jumat_last_piket[@]})

EOF
}

source "$HOME/Documents/School/siswa_db/siswa_9d-akrab.sh"
source "$LAST_PATH" || echo "[i] Gagal menyumberkan informasi terakhir!" > /dev/stderr

case "$hari" in
	# Senin)
	# 	;;
	# Selasa)
	# 	eskur="(bagi yang eskur pulang pk. 16:15)"
	# 	;;
	# Jumat)
	# 	eskur="(bagi yang eskur pulang pk. 16:15)"
	# 	;;
	Rabu)

		[[ $MAPELS_ONLY -ne 1 ]] && [[ "$1" != "preview" ]] && read -p "→ Sport time? [y/n] > " tmp
		if [[ "$tmp" == "n" ]]
		then
			sport_time=n
		fi
		j_pulang_pre="16:15"
		j_pulang_tmp="16:15"
		eskur="(ada eskur Pramuka)"
		;;
esac

case "$hari" in
	Sabtu|Minggu)
		hari="Senin"
		tanggal="`date -d 'monday' '+%d %B %Y'`"
		;;
esac

case "$hari" in
	Senin)
		baju="${FORMAT_BOLD}seragam putih kotak lengkap${FORMAT_BOLD}, membawa ${FORMAT_BOLD}jas lab${FORMAT_BOLD}"
		;;
	Selasa)
		baju="${FORMAT_BOLD}seragam putih kotak lengkap${FORMAT_BOLD}"
		;;
	Rabu)
		if [[ "$sport_time" == "n" ]]
		then
			# baju="${FORMAT_BOLD}seragam Pramuka lengkap${FORMAT_BOLD} dengan ${FORMAT_BOLD}kacu, ikat pinggang${FORMAT_BOLD}; membawa topi Pramuka 🤠"
			baju="${FORMAT_BOLD}seragam Pramuka lengkap${FORMAT_BOLD} dengan ${FORMAT_BOLD}kacu, ikat pinggang${FORMAT_BOLD}"
		else
			# baju="${FORMAT_BOLD}baju olah raga atau kaos bebas${FORMAT_BOLD} (ada sport time), ${FORMAT_BOLD}membawa seragam Pramuka lengkap${FORMAT_BOLD} dengan ${FORMAT_BOLD}kacu${FORMAT_BOLD} dan ${FORMAT_BOLD}ikat pinggang${FORMAT_BOLD} dan ${FORMAT_BOLD}topi Pramuka${FORMAT_BOLD} 🤠"
			baju="${FORMAT_BOLD}baju olah raga atau kaos bebas${FORMAT_BOLD} (ada sport time), ${FORMAT_BOLD}membawa seragam Pramuka lengkap${FORMAT_BOLD} dengan ${FORMAT_BOLD}kacu${FORMAT_BOLD} dan ${FORMAT_BOLD}ikat pinggang${FORMAT_BOLD}"
		fi
	#	eskur="(ada eskur pramuka)"
		;;
	Kamis)
		baju="${FORMAT_BOLD}baju olahraga${FORMAT_BOLD}, membawa ${FORMAT_BOLD}seragam putih kotak${FORMAT_BOLD}."
		;;
	Jumat)
		baju="${FORMAT_BOLD}baju batik${FORMAT_BOLD} dengan ${FORMAT_BOLD}bawahan biru${FORMAT_BOLD}"
		;;

		# yo wes PJJ lagi
		#baju="${FORMAT_BOLD}baju olahraga${FORMAT_BOLD}"
esac


declare -A kode=(
[1]="PPkn"
[2]="Agama"
[3]="Agama"
[4]="PPKn"
[5]="PPKn"
[6]="B. Indonesia"
[7]="B. Indonesia"
[8]="B. Indonesia"
[9]="B. Indonesia"
[10]="Inggris"
[11]="Inggris"
[12]="Inggris"
[13]="Matematika"
[14]="Matematika"
[15]="Matematika"
[16]="Matematika"
[17]="Fisika"
[18]="Fisika"
[19]="Fisika"

[21]="Biologi"
[22]="Biologi"
[23]="Biologi"
[24]="IPS"
[25]="IPS"
[26]="IPS"
[27]="PJOK"
[28]="PJOK"
[39]="Sunda"
[40]="Mandarin"
[41]="Mandarin"
[47]="Native"
[LAB]="Laboratorium"
[PRA]="Prakarya"
[SB]="Seni budaya"
[NAT]="Native"
[LABF]="Lab Fisika"
[LABB]="Lab Biologi"
)

declare -A mapel=(

# Has fake arrays

["Senin"]='(18 NAT 14 LABF LABB 22 8)'
["Selasa"]='(14 10 PRA 28 18)'
["Rabu"]='(SB 25 4 2 40)'
["Kamis"]='(28 10 SB 8 39 18 2)'
["Jumat"]='(8 14 4 22 25 10)'
["Sabtu"]='()'
["Minggu"]='()'
)

if [[ "$MAPELS_ONLY" -eq 1 ]]
then
	mapels
	exit 0
fi


case "$1" in
	utils)
		case "$2" in
			query)
				echo "${kode[$3]}"
				exit
				;;
			next-hint)
				hint_next_mapel "$3"
				exit
				;;
		esac
		;;
	preview)
		echo 
		;;
	*)
		read -p "→ Jam masuk? [06:45] > " j_masuk
		read -p "→ Jam pulang? [$j_pulang_tmp] > " j_pulang
		if [[ -z "$j_pulang" ]] && [[ -n "$j_pulang_pre" ]]
		then
			j_pulang="$j_pulang_pre"
		fi
		read -p "→ Seragam? [${baju//\${FORMAT_BOLD}}] > " baju_tmp

		read -e -p "→ Mapel custom? " -a mapels_custom

		read -p "→ PR [y/n] > " tmp
		if [[ "$tmp" == "y" ]]
		then
			read -p "→ Query Notion db? > " tmp
			if [[ "$tmp" == "y" ]]
			then
				notion_integration_retrive_tasks
			fi

			read -p "→ Manually enter tasks? > " tmp
			if [[ "$tmp" == "y" ]]
			then

				n=1
				echo "$n)" > /dev/stderr
				read -e -p "Mapel: " input_pr_mapel
				read -e -p "Tugas: " input_pr_tugas
				hint_next_mapel "$input_pr_mapel"
				read -e -p "Tenggat: " input_pr_tenggat

				[[ -n "$input_pr_mapel" ]] && pr_mapel=("$input_pr_mapel")
				[[ -n "$input_pr_tugas" ]] && pr=("$input_pr_tugas")
				[[ -n "$input_pr_tenggat" ]] && pr_tenggat=("$input_pr_tenggat") || pr_tenggat=("null")

				(( n++ ))

				while [[ -n "$input_pr_mapel" ]] || [[ -n "$input_pr_tugas" ]]
				do
					echo > /dev/stderr

					echo "$n)" > /dev/stderr
					read -e -p "Mapel: " input_pr_mapel
					[[ -z "$input_pr_mapel" ]] && break
					read -e -p "Tugas: " input_pr_tugas
					hint_next_mapel "$input_pr_mapel"
					read -e -p "Tenggat: " input_pr_tenggat


					[[ -n "$input_pr_mapel" ]] && pr_mapel+=("$input_pr_mapel")
					[[ -n "$input_pr_tugas" ]] && pr+=("$input_pr_tugas")
					[[ -n "$input_pr_tenggat" ]] && pr_tenggat+=("$input_pr_tenggat") || pr_tenggat+=("null")

					(( n++ ))
				done
			fi
		fi


		
		read -p "→ Penilaian [y/n] > " tmp
		if [[ "$tmp" == "y" ]]
		then
			n=1
			echo "$n)" > /dev/stderr
			read -e -p "Penilaian: " input_penilaian
			read -e -p "Materi: " input_penilaian_materi

			[[ -n "$input_penilaian" ]] && penilaian=("$input_penilaian")
			[[ -n "$input_penilaian_materi" ]] && penilaian_materi=("$input_penilaian_materi") || penilaian_materi=("null")

			(( n++ ))

			while [[ -n "$input_penilaian" ]]
			do
				echo > /dev/stderr

				echo "$n)" > /dev/stderr
				read -e -p "Penilaian: " input_penilaian
				[[ -z "$input_penilaian" ]] && break
				read -e -p "Materi: " input_penilaian_materi

				[[ -n "$input_penilaian" ]] && penilaian+=("$input_penilaian")
				[[ -n "$input_penilaian_materi" ]] && penilaian_materi+=("$input_penilaian_materi") || penilaian_materi+=("null")

				(( n++ ))
			done
		fi

		read -p "→ Catatan? [y/n] > " tmp
		if [[ "$tmp" == "y" ]]
		then
			n=1
			read -e -p "$n) " input_catatan
			[[ -n "$input_catatan" ]] && catatan=("$input_catatan")
			(( n++ ))

			while [[ -n "$input_catatan" ]]
			do
				read -e -p "$n) " input_catatan
				[[ -n "$input_catatan" ]] && catatan+=("$input_catatan")
				(( n++ ))
			done
		fi

		if [[ -t 0 ]] # only print these when stdin is open
		then
			echo -e " \nRenungan Pagi" > /dev/stderr
			echo "Terakhir: ${siswa_9d[$last_renungan_1]} (no. $last_renungan_1), ${siswa_9d[$last_renungan_2]} (no. $last_renungan_2)" > /dev/stderr
			echo -e "${STYLE_BOLD}8 siswa dalam range renungan:${STYLE_RESET}" > /dev/stderr

			for i in $(seq $((last_renungan_1 - 3)) $((last_renungan_2 + 3)) | grep -vx 0)
			do
				no=$((($i + 31) % (${#siswa_9d[@]})+1))
				if [[ $no -eq $last_renungan_1 ]] || [[ $no == "$last_renungan_2" ]]
				then
					echo -e "\e[1;33m $no) ${siswa_9d[$no]}${STYLE_RESET}" > /dev/stderr
				else
					echo " $no) ${siswa_9d[$no]}" > /dev/stderr
				fi
			done
		fi

		tmp="boo"
		until isint_exclude_empty $tmp && [[ $tmp -le ${#siswa_9d[@]} ]]
		do
			read -p "→ Siswa 1: [$(((last_renungan_1 + 2) % ${#siswa_9d[@]}))]> " tmp
		done
		if [[ -z "$tmp" ]] 
		then
			siswa_renungan_1="$(((last_renungan_1 + 2) % ${#siswa_9d[@]}))"
		else
			siswa_renungan_1="$tmp"
		fi

		tmp=boo
		until isint_exclude_empty $tmp && [[ $tmp -le ${#siswa_9d[@]} ]]
		do
			read -p "→ Siswa 2: [$(((last_renungan_2 + 2) % ${#siswa_9d[@]}))]> " tmp
		done
		if [[ -z "$tmp" ]] 
		then
			siswa_renungan_2="$(((last_renungan_2 + 2) % ${#siswa_9d[@]}))"
		else
			siswa_renungan_2="$tmp"
		fi


		if [[ -t 0 ]] 
		then
			echo -e "\nDoa pulang" > /dev/stderr
			echo "Terakhir: ${siswa_9d[$last_doa_pulang]} (no. $last_doa_pulang)" > /dev/stderr

			echo -e "${STYLE_BOLD}5 siswa dalam range doa:${STYLE_RESET}" > /dev/stderr

			for i in $(seq $((last_doa_pulang - 2)) $((last_doa_pulang + 2)) | grep -vx 0)
			do
				no=$(((i + 31) % (${#siswa_9d[@]} + 1)))
				if [[ $no -eq $last_doa_pulang ]]
				then
					echo -e "\e[1;33m $no) ${siswa_9d[$no]}${STYLE_RESET}" > /dev/stderr
				else
					echo " $no) ${siswa_9d[$no]}" > /dev/stderr
				fi
			done
		fi

		# if [[ "$hari" != "Rabu" ]]
		# then
			tmp="boo"
			until isint_exclude_empty $tmp && [[ $tmp -le ${#siswa_9d[@]} ]]
			do
				read -p "→ Doa pulang: [$(((last_doa_pulang + 30) % (${#siswa_9d[@]} - 1)))] > " tmp
			done
			if [[ -z "$tmp" ]]
			then

				siswa_doa_pulang="$(((last_doa_pulang + 30) % (${#siswa_9d[@]} - 1)))"
			else
				siswa_doa_pulang="$tmp"
			fi
		# else
			# siswa_doa_pulang=""
		# fi


		if [[ $(date '+%-m%d%Y') -gt $timestamp ]]
		then
			if [ -t 0 ]
			then
				echo -en "→ \e[0;31mSimpan data? [y/n]> $STYLE_RESET" > /dev/stderr
				read tmp
				[[ "$tmp" == "y" ]] && save_data
			else
				echo -e "\e[0;31m→ Saved data.$STYLE_RESET"
				save_data
			fi
		fi
	;;
esac

echo -e "------------------------------\n" > /dev/stderr
echo -e "🗓️ ${FORMAT_BOLD}$hari, $tanggal${FORMAT_BOLD}"

[[ -n "$baju_tmp" ]] && baju="$baju_tmp"
[[ -z "$j_masuk" ]] && j_masuk="06:45"

[[ -z "$j_pulang" ]] && j_pulang="14:35"

# Pas udah ada eskur, add the code
# to change the jam pulang

#if [[ "`date +%A`" == "Rabu

echo
echo -e "🕡 Masuk pk. $j_masuk - $j_pulang $eskur"
echo -e "👕 Memakai $baju"
echo


mapels


if [[ -n "${pr}" ]]
then
	echo

	echo "📔 ${FORMAT_BOLD}PR${FORMAT_BOLD} (https://gg.gg/pr-tugas-9d-2023)"
	for (( i = 0; i < ${#pr[@]}; i++ ))
	do
		[[ "${pr_tenggat[$i]}" == "null" ]] && echo "$((i+1))) ${FORMAT_BOLD}${pr_mapel[$i]}${FORMAT_BOLD}: ${pr[$i]}" || echo "$((i+1))) ${FORMAT_BOLD}${pr_mapel[$i]}${FORMAT_BOLD}: ${pr[$i]} ${FORMAT_BOLD}(🗓️ tenggat ${pr_tenggat[$i]})${FORMAT_BOLD}"
	done
fi

if [[ -n "$penilaian" ]]
then
	echo

	echo "📄 ${FORMAT_BOLD}Penilaian${FORMAT_BOLD}"
	for (( i = 0; i < ${#penilaian[@]}; i++ ))
	do
		[[ "${penilaian_materi[$i]}" == null ]] && echo "$((i+1))) ${FORMAT_BOLD}${penilaian[$i]}${FORMAT_BOLD}" || echo "$((i+1))) ${FORMAT_BOLD}${penilaian[$i]}${FORMAT_BOLD}: ${penilaian_materi[$i]}"
	done
fi

if  [[ -n "${catatan}" ]] || [[ "Senin|Jumat" =~ "$hari" ]]
then

	echo

	echo "🖊️ ${FORMAT_BOLD}Catatan${FORMAT_BOLD}"
	case "$hari" in
		Senin)
			echo "• Membawa Alkitab (apabila perlu dikumpul di lemari)"
			;;
		Selasa)
			echo "• Ada R&R."
			;;
		Jumat)
			echo "• Membawa pulang Alkitab (apabila ada di lemari)"
			# echo "• Ada R&R (buku fisik)."
			;;
		Rabu)
			[[ "$sport_time" == "n" ]] && echo "• ${FORMAT_BOLD}Tidak${FORMAT_BOLD} ada sport time." || echo "• Ada sport time." 
			;;
	esac
	for (( i = 0; i < ${#catatan[@]}; i++ ))
	do
		echo "$((i+1))) ${catatan[$i]}"
	done
fi

# also has fake arrays. BASH CMON PLS ADD SUPPORT 2 DIMENSIONAL ARRAYS
declare -A data_piket=(
["Senin"]='(13 9 2 1 3 4)'
["Selasa"]='(22 30 6 7 8 10)'
["Rabu"]='(5 11 14 12 15 16)'
["Kamis"]='(23 17 19 20 21 24)'
["Jumat"]='(18 25 26 27 28 29)'
)

case "$hari" in
	*)
		echo -e "\n📱 ${FORMAT_BOLD}Piket Menjaga Handphone${FORMAT_BOLD}"
		eval "piket_terakhir=(\${${hari@L}_last_piket[@]})"

		piket_1=$(((${piket_terakhir[0]} + 2 ) % 6))
		piket_2=$(((${piket_terakhir[1]} + 2 ) % 6))
		eval "data_piket_hari_ini=${data_piket[${hari}]}"
		siswa_piket_1=${data_piket_hari_ini[$piket_1]}
		siswa_piket_2=${data_piket_hari_ini[$piket_2]}
		eval "${hari@L}_last_piket=($siswa_piket_1 $siswa_piket_2)"

		echo "• ${siswa_9d[$siswa_piket_1]}"
		echo "• ${siswa_9d[$siswa_piket_2]}"
		;;
esac


echo
echo "• Renungan pagi: ${FORMAT_BOLD}${siswa_9d[$siswa_renungan_1]}${FORMAT_BOLD} dan ${FORMAT_BOLD}${siswa_9d[$siswa_renungan_2]}${FORMAT_BOLD}"
[[ -n "$siswa_doa_pulang" ]] && echo "• Doa pulang: ${FORMAT_BOLD}${siswa_9d[$siswa_doa_pulang]}${FORMAT_BOLD}"

sep
echo "${FORMAT_BOLD}🗒 Jadwal PH dan Kegiatan${FORMAT_BOLD}: https://gg.gg/9d-jadwalkeg-2023"

if "$HOME/Documents/School/siswa_db/tanggal-lahir-9d.sh" &> /dev/null
then
	sep
	"$HOME/Documents/School/siswa_db/tanggal-lahir-9d.sh"
fi

if "$HOME/Documents/School/siswa_db/tanggal-lahir-9d.sh" tom &> /dev/null
then
	sep
	"$HOME/Documents/School/siswa_db/tanggal-lahir-9d.sh"
fi

